
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (1, 'USD', 'US Dollar', 1.1355, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (2, 'JPY', 'Japanese yen', 130.56, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (3, 'BGN', 'Bulgarian lev', 1.9558, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (4, 'CZK', 'Czech koruna', 24.818, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (5, 'DKK', 'Danish krone', 7.4382, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (6, 'GBP', 'Pound sterling', 0.84135, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (7, 'HUF', 'Hungarian forint', 367.71, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (8, 'PLN', 'Polish zloty', 4.5895, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (9, 'RON', 'Romanian leu', 4.9483, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (10, 'SEK', 'Swedish krona', 10.2958, 0, CURRENT_TIMESTAMP());
insert into EURO_FOREIGN_EXCHANGE_REFERENCE_RATE values (11, 'INR', 'Indian rupee',  84.3949, 0, CURRENT_TIMESTAMP());
